apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: store
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: aacecandev/playground-api:1.3.40
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          value: redis-cluster-0.redis-cluster-headless.redis.svc.cluster.local:6379
        - name: STORE_PORT
          value: ":8080"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
