server:
  additionalApplications:
    - name: store
      namespace: argocd
      project: store
      source:
        repoURL: https://github.com/aacecandev/playground.git
        targetRevision: HEAD
        path: argocd/apps
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
