---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  destination:
    namespace: registry
    server: https://kubernetes.default.svc
  project: store
  source:
    # helm:
    #   parameters:
    #     - name: build.enabled
    #       value: "false"
    #     - name: deploy.route.enabled
    #       value: "false"
    #     - name: image.name
    #       value: quay.io/redhatworkshops/gitops-helm-quarkus
    chart: harbor/harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.9.3
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
