name: "Build and push API"
on:
  push:
    tags:
      - "api-*.*.*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get image tag and Dockerfile folder
        id: tag-folder
        ## Step variables explanation
        # REF_NAME=store-1.0.0
        # COMPONENT=store
        # IMAGE_TAG=1.0.0
        run: |
          REF_NAME=${{ github.ref_name }}
          COMPONENT=${REF_NAME%-*}
          TAG=${REF_NAME##*-}
          echo "COMPONENT=${COMPONENT}" >> ${GITHUB_OUTPUT}
          echo "TAG=${TAG}" >> ${GITHUB_OUTPUT}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.repository }}-
          restore-keys: ${{ runner.os }}-buildx--${{ github.repository }}

      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Prepare Docker image metadata
        id: docker_image_metadata
        uses: docker/metadata-action@v4
        with:
          images: "docker.io/${{ github.actor}}/${{ steps.tag-folder.outputs.COMPONENT }}"
          flavor: latest=auto
          tags: |
            type=semver,pattern={{version}},value=${{ steps.tag-folder.outputs.TAG }}
            type=sha,format=long
          labels: |
            org.opencontainers.image.version=${{ steps.tag-folder.outputs.TAG }}

      # - name: Push to Docker Hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     platforms: linux/amd64
      #     push: true
      #     tags: |
      #       ${{ github.actor }}/mairror-api:${{ github.ref_name }}
      #       mairror/mairror-api:latest
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
            rm -rf /tmp/.buildx-cache
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache