name: "Build and push API"
on:
  push:
    tags:
      - "api-*.*.*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get image tag and Dockerfile folder
        id: tag-folder
        ## Step variables explanation
        # REF_NAME=store-1.0.0
        # COMPONENT=store
        # IMAGE_TAG=1.0.0
        run: |
          REF_NAME=${{ github.ref_name }}
          COMPONENT=${REF_NAME%-*}
          TAG=${REF_NAME##*-}
          echo "COMPONENT=${COMPONENT}" >> ${GITHUB_OUTPUT}
          echo "TAG=${TAG}" >> ${GITHUB_OUTPUT}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Login to ghcr.io
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

            # "ghcr.io/${{ github.repository }}-${{ steps.tag-folder.outputs.COMPONENT }}"
      - name: Prepare Docker image metadata
        id: docker_image_metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository }}-${{ steps.tag-folder.outputs.COMPONENT }}
          flavor: latest=auto
          tags: |
            type=semver,pattern={{version}},value=${{ steps.tag-folder.outputs.TAG }}
            type=sha,format=long
          labels: |
            org.opencontainers.image.version=${{ steps.tag-folder.outputs.TAG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ steps.tag-folder.outputs.COMPONENT }}
          file: ${{ steps.tag-folder.outputs.COMPONENT }}/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.docker_image_metadata.outputs.tags }}
          labels: ${{ steps.docker_image_metadata.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
