name: SBOM

on:
  release:
    types: [published]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Anchore SBOM Action
        uses: anchore/sbom-action@v0.13.3
        with:
          path: "."
          format: spdx-json
          artifact-name: sbom.syft.spdx.json
          output-file: sbom.syft.spdx.json
          dependency-snapshot: true
